In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('IRIS.csv')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
df.sample(5)

     sepal_length  sepal_width  petal_length  petal_width          species
40            5.0          3.5           1.3          0.3      Iris-setosa
142           5.8          2.7           5.1          1.9   Iris-virginica
105           7.6          3.0           6.6          2.1   Iris-virginica
75            6.6          3.0           4.4          1.4  Iris-versicolor
36            5.5          3.5           1.3          0.2      Iris-setosa

In [6]:
from ydata_profiling import ProfileReport
prof = ProfileReport(df)
prof.to_file(output_file='output1.html')

C:\Users\jitud\AppData\Local\Temp\ipykernel_20108\4293489005.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 5/5 [00:00<00:00, 263.40it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]